function Hd = filter_physio
%FILTER_PHYSIO Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.13 and the Signal Processing Toolbox 6.16.
%
% Generated on: 21-Jun-2013 18:23:36
%

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
% Fs = 48000;  % Sampling Frequency
% 
% Fstop1 = 10;          % First Stopband Frequency
% Fpass1 = 11;          % First Passband Frequency
% Fpass2 = 50;          % Second Passband Frequency
% Fstop2 = 60;          % Second Stopband Frequency
% Astop1 = 60;          % First Stopband Attenuation (dB)
% Apass  = 1;           % Passband Ripple (dB)
% Astop2 = 80;          % Second Stopband Attenuation (dB)
% match  = 'passband';  % Band to match exactly
% 
% % Construct an FDESIGN object and call its CHEBY1 method.
% h  = fdesign.lowpass(50, 51, 1, 60);
% Hd = design(h);
% % [EOF]
d = fdesign.highpass(0.005, 0.01, 80, 1);
Hd = design(d); % Uses the default equiripple method.


% d=fdesign.lowpass('Fp,Fst,Ap,Ast',50,60,1,60);
% Hd = design(d,'butter'); %Lowpass FIR filter
